image:
  repository: quay.io/sysdig/php-fpm-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.3.3"

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 128m
    memory: 128Mi
  requests:
    cpu: 64m
    memory: 64Mi

sysdig:
  # The name of the integration
  integrationType:
  
ubi: false

env:
  web: 
    listen_address: 9253
    telemetry_path: /metrics
  phpfpm:
    scrape_uri: tcp://127.0.0.1:9000/status
    fix_process_count: false
  log: 
    level: info