# Default values for promcat-postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/sysdig/postgresql-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.11.2"

port: 9187

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secretName: "postgresql-exporter"

sysdig:
  namespaceName:
  workloadType:
  workloadName:
  exporterNamespaceName:
  integrationType:
# The name of the integration

dbInstance:
  host: "localhost"
  port: "5432"
  database: "postgres"
  sslmode: "disable"
  sslRootCertEnabled: false

exporterParams:
  autoDiscoverDatabases: true
  disableSettingsMetrics: false
  excludeDatabases: ""

customMetrics: ""
ubi: false