image:
  repository: quay.io/sysdig/memcached-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.10.6"


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "128Mi"
    cpu: "64m"
  requests:
    memory: "64Mi"
    cpu: "32m"

# This value is only used in Sysdig annotations
integrationType:

port: 9150
url:
  name: ""
ubi: false