image:
  apache:
    repository: bitnami/apache-exporter
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.7"
  grok:
    repository: palobo/grok_exporter
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "128Mi"
    cpu: "64m"
  requests:
    memory: "64Mi"
    cpu: "32m"

# This value is only used in Sysdig annotations
integrationType:

apacheExporter:
  port: 9117

grokExporter:
  port: 9144

configmap: false
ubi: false