{{ if not .Values.onlyCreateJMXConfigMap  }}
spec:
  template:
    metadata:
      annotations:
      {{- if .Values.sysdigAnnotations }}
      {{- include "jmx-exporter.sysdigAnnotations" . | nindent 8 }}
      {{ else }}
      {{- include "jmx-exporter.prometheusAnnotations" . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: "{{ include "jmx-exporter.finalIntegrationName" . }}-jmx-exporter"
        {{- if not .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- end }}
        {{- if .Values.ubi }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}-ubi"
        {{- end }}
        args: [ "{{ .Values.port }}", "{{ .Values.configFileLocation }}" ]
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/jmx_exporter/config.yml
          name: {{ include "jmx-exporter.finalConfigmapName" . }}
          subPath: config.yml        
      volumes:
        - name: {{ include "jmx-exporter.finalConfigmapName" . }}
          configMap:
              name: {{ include "jmx-exporter.finalConfigmapName" . }}
{{- end }}
