replicaCount: 1

image:
  repository: quay.io/sysdig/redis-exporter
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.43.2"


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

url:
  name: redis
  port: 6379

namespaceName: "redis"
  # The namespace of the application that the exporter will connect to in order to generate metrics

workloadType: "deployment"
  # The kubernetes workload type of the application the exporter will connect to. 
  # Possible values: deployment, statefulset, daemonset, pod

workloadName: "redis"
  # The name of the workload of the application that the exporter will connect to.

exporterNamespaceName: "redis"
  # The namespace where the exporter will be deployed

integrationType: "redis"
  # The name of the integration
ubi: false

redisTlsConfig:
  # Use TLS configuration
  enabled: false
  # Whether to to skip TLS verification
  skipTlsVerification: false
  # All secrets key about TLS config will be mounted into this path
  mountPath: /tls
  # REDIS_EXPORTER_TLS_CA_CERT_FILE will be set to /tls/tls-ca-cert.crt
  caCertFile:
    secret:
      name: ""
      key: ""
  # REDIS_EXPORTER_TLS_CLIENT_KEY_FILE  will be set to /tls/tls-client-key.key
  clientKeyFile:
    secret:
      name: ""
      key: ""
  # REDIS_EXPORTER_TLS_CLIENT_CERT_FILE will be set to /tls/tls-client-cert.crt
  clientCertFile:
    secret:
      name: ""
      key: ""
  # REDIS_EXPORTER_TLS_SERVER_KEY_FILE will be set to /tls/tls-server-key.key
  serverKeyFile:
    secret:
      name: ""
      key: ""
  # REDIS_EXPORTER_TLS_SERVER_CERT_FILE will be set to /tls/tls-server-cert.crt
  serverCertFile:
    secret:
      name: ""
      key: ""

auth:
  # Use password authentication
  enabled: false
  # Use existing secret (ignores redisPassword)
  secret:
    name: ""
    key: ""
  # Redis password (when not stored in a secret)
  redisPassword: ""
  # Redis user (version 6.X and above)
  redisUser: ""

# Enable debug log level for the exporter
enableDebug: true